name: Continous Deployment (Java Edition)

on:
  release:
    types: [published]

jobs:
  release:

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: actions/setup-scala@v11
        with:
          java-version: adopt@1.11
      - name: continous integration
        run : |
          sbt test
      - name: prepare
        run: |
          sbt compile
      - name: Package and Upload
        env:
          ADK_VERSION: ${{github.event.release.tag_name }}
          SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD }}
        run: |
          sbt publishSigned
          sbt sonatypeRelease