name: Continous Deployment (Java Edition)

on:
  push:
    branches: [ master, main ]
    tags: [ "*" ]

jobs:
  release:

    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: actions/setup-scala@v11
        with:
          java-version: adopt@1.11
      - name: continous integration
        run : |
          sbt test
      - uses: olafurpg/setup-scala@v13
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}